name: CI Pipeline for Encryption Bot

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Clean up lock file
      - name: Clean up lock file
        run: |
          rm -f bot_lock.lock

      # Set up Python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev libffi-dev

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Lint the code with flake8
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --max-line-length=120 --exclude=venv

      # Run tests (if test files exist)
      - name: Run tests
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          python -m unittest discover -s tests -p "test_*.py" || echo "No tests found or tests failed"

      # Run the bot in a test mode (optional, for basic script validation)
      - name: Validate script execution
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          python bot.py --test-mode
